# Generated by Django 2.1.1 on 2018-10-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.IntegerField()),
                ('media_source', models.CharField(max_length=200)),
                ('media_source_id', models.IntegerField()),
                ('media_lastUpd', models.DateTimeField()),
            ],
        ),
    ]
