from .index import *
from .profiles import *
from .settings import *
from .donate import *
from .movies import *
from .shows import *
from .music import *
from .runsync import *
from .logs import *
from .about import *
from .updates import *
from .systemsettings import *